SELECT 
    departments.depart_name AS departments_depart_name,
    groups.department_code AS groups_department_code,
    groups.group_semestr AS groups_group_semestr,
    groups.group_formaobuch AS groups_group_formaobuch,
    groups.group_code AS groups_group_code,
    groups.group_name AS groups_group_name,
    student.student_id AS student_student_id,
    student.student_lastname AS student_student_lastname,
    student.student_name AS student_student_name,
    student.student_middlename AS student_student_middlename,
    student.student_birthday AS student_student_birthday,
    student.nationality_code AS student_nationality_code,
    student.student_addr AS student_student_addr,
    student.student_docfrom AS student_student_docfrom,
    student.student_prikaz AS student_student_prikaz,
    student.student_prikazdate AS student_student_prikazdate,
    student.student_photo AS student_student_photo,
    student.student_propiska AS student_student_propiska,
    student.student_phone AS student_student_phone,
    student.student_social AS social_student,
    student.student_docdate AS studl_docdate,
    spr_zachislenie.zachislenie_name AS spr_zachislenie_zachislenie_name,
    spr_settingsen.`A_NAMEL` AS spr_settingsen_A_NAMEL,
    spr_settingsen.`A_ADRES` AS spr_settingsen_A_ADRES,
    spr_settingsen.`A_PHONE` AS spr_settingsen_A_PHONE,
    spr_settingsen.`A_FAX` AS spr_settingsen_A_FAX,
    spr_settingsen.`A_RECTOR` AS spr_settingsen_A_RECTOR,
    spr_settingsen.`A_UOTDEL` AS spr_settingsen_A_UOTDEL,
    spr_settingsen.`A_WWW` AS spr_settingsen_A_WWW,
    spr_settingsen.`A_EMAIL` AS spr_settingsen_A_EMAIL,
    spr_settingskg.`A_NAMEL` AS spr_settingskg_A_NAMEL,
    spr_settingskg.`A_ADRES` AS spr_settingskg_A_ADRES,
    spr_settingskg.`A_PHONE` AS spr_settingskg_A_PHONE,
    spr_settingskg.`A_FAX` AS spr_settingskg_A_FAX,
    spr_settingskg.`A_RECTOR` AS spr_settingskg_A_RECTOR,
    spr_settingskg.`A_WWW` AS spr_settingskg_A_WWW,
    spr_settingskg.`A_EMAIL` AS spr_settingskg_A_EMAIL,
    spr_settingskg.`PHOTO_INF` AS spr_settingskg_PHOTO_INF,
    spr_settings.`A_NAMEL` AS spr_settings_A_NAMEL,
    spr_settings.`A_ADRES` AS spr_settings_A_ADRES,
    spr_settings.`A_PHONE` AS spr_settings_A_PHONE,
    spr_settings.`A_FAX` AS spr_settings_A_FAX,
    spr_settings.`A_RECTOR` AS spr_settings_A_RECTOR,
    spr_settings.`A_WWW` AS spr_settings_A_WWW,
    spr_settings.`A_EMAIL` AS spr_settings_A_EMAIL,
    spr_settingskg.`A_UOTDEL` AS spr_settingskg_A_UOTDEL,
    spr_settings.`A_UOTDEL` AS spr_settings_A_UOTDEL,
    spr_settingskg.`A_NAMES` AS spr_settingskg_A_NAMES,
    spr_settings.`A_NAMES` AS spr_settings_A_NAMES,
    spr_settingsen.`A_NAMES` AS spr_settingsen_A_NAMES,
    spForm.formobuch_name AS formobuchName,
    sp_nat.nationality_name AS Nationality
FROM
    departments departments
INNER JOIN groups groups ON departments.depart_code = groups.department_code
INNER JOIN student student ON groups.group_code = student.group_code
INNER JOIN spr_formobuch spForm ON groups.group_formaobuch=spForm.formobuch_code
INNER JOIN spr_zachislenie spr_zachislenie ON student.zachislenie_code = spr_zachislenie.zachislenie_code
INNER JOIN spr_nationality sp_nat ON student.nationality_code=sp_nat.nationality_code,
    spr_settingsen spr_settingsen,
    spr_settingskg spr_settingskg,
    spr_settings spr_settings
WHERE
    student.student_id = '...'
