package bup;

import DAO.DisciplineDAO;
import bdoc.dbconnector;
import bdoc.mainBdoc;
import countClocks.CountClock;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Altynbek
 */
public class AddBupForm extends javax.swing.JFrame {
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    public AddBupForm() {
        conn = dbconnector.getConnection();
        initComponents();
        fillDisciplineCombo();
        fillYears();
    }
    
    private void fillDisciplineCombo(){
        
        List<String> discNames = new ArrayList<String>();
        
        DisciplineDAO fill = new DisciplineDAO();
        discNames = fill.getDisciplineNameList();
        
        for(int i=0; i < discNames.size(); i++){
            bup_disс_name.addItem(discNames.get(i));
        }
        
    }
    
    private void fillYears(){
        
        List<String> _startyear = new ArrayList<>();
        List<String> _endYear = new ArrayList<>();
        
        DisplayBUPYears dBup = new DisplayBUPYears();
        
        _startyear = dBup.fillComboBupStartYears();
        _endYear = dBup.fillComboBupEndYears();
        
        for(int i=0; i < _startyear.size(); i++){
            bup_year_s.addItem(_startyear.get(i));
        }
        
        for(int i=0; i < _endYear.size(); i++){
            bup_year_e.addItem(_endYear.get(i));
        }
        
    } 
    
    public void updateBupTable( JTable table ){
    
    try {
        String sql = "SELECT \n" +
                    "bup_year.bup_dis_code AS 'Код дисциплины', \n" +
                    "spr_discipline.disc_name AS 'Наименование дисциплины',\n" +
                    "bup_year.bup_vsego_chas AS 'Всего час', \n" +
                    "bup_year.bup_kredit_vsego AS 'Кредиты', \n" +
                    "bup_year.bup_aud_chas AS 'Аудиторн', \n" +
                    "bup_year.bup_lec_chas AS 'Лекции', \n" +
                    "bup_year.bup_prac_chas AS 'Семинары', \n" +
                    "bup_year.bup_ind_chas AS 'Индив', \n" +
                    "bup_year.bup_srs_chas AS 'СРС', \n" +
                    "bup_year.bup_zachet AS 'Зачет', \n" +
                    "bup_year.bup_ekzamen AS 'Экзамен', \n" +
                    "bup_year.bup_kur_rabota AS 'Курс. раб', \n" +
                    "bup_year.bup_kontr_rab AS 'Контр. раб', \n" +
                    "bup_year.bup_nir AS 'НИР', \n" +
                    "bup_year.bup_semestr AS 'Семестр' \n" +
                    "FROM bup_year \n" +
                    "LEFT JOIN spr_discipline\n" +
                    "ON bup_year.bup_dis_code=spr_discipline.disc_code\n" +
                    "ORDER BY bup_dis_code ASC";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
           // JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bup_disc_label = new javax.swing.JLabel();
        bup_disс_name = new javax.swing.JComboBox();
        bup_disc_code = new javax.swing.JTextField();
        bup_clock_label = new javax.swing.JLabel();
        bup_clock_field = new javax.swing.JFormattedTextField();
        bup_credits_label = new javax.swing.JLabel();
        bup_credits_field = new javax.swing.JFormattedTextField();
        raspred_uchVrem_panel = new javax.swing.JPanel();
        bup_auditorn_label = new javax.swing.JLabel();
        bup_lection_label = new javax.swing.JLabel();
        bup_practika_label = new javax.swing.JLabel();
        bup_individual_label = new javax.swing.JLabel();
        bup_srs_label = new javax.swing.JLabel();
        bup_auditorn_field = new javax.swing.JFormattedTextField();
        bup_lection_field = new javax.swing.JFormattedTextField();
        bup_practika_field = new javax.swing.JFormattedTextField();
        bup_individual_field = new javax.swing.JFormattedTextField();
        bup_srs_field = new javax.swing.JFormattedTextField();
        bup_zachet_label = new javax.swing.JLabel();
        bup_zachet_field = new javax.swing.JFormattedTextField();
        bup_ekzamen_label = new javax.swing.JLabel();
        bup_ekzamen_field = new javax.swing.JFormattedTextField();
        bup_kursov_label = new javax.swing.JLabel();
        bup_kursov_field = new javax.swing.JFormattedTextField();
        bup_kontol_label = new javax.swing.JLabel();
        bup_kontrol_label = new javax.swing.JFormattedTextField();
        bup_nir_label = new javax.swing.JLabel();
        bup_nir_field = new javax.swing.JFormattedTextField();
        bup_semestr_label = new javax.swing.JLabel();
        bup_semestr_combo = new javax.swing.JComboBox();
        bup_add_save = new javax.swing.JButton();
        bup_add_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bup_year_s = new javax.swing.JComboBox();
        bup_year_e = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bup_disc_label.setText("Код дисциплины");

        bup_disс_name.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                bup_disс_namePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        bup_disc_code.setEditable(false);

        bup_clock_label.setText("Всего час:");

        bup_clock_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bup_clock_fieldKeyPressed(evt);
            }
        });

        bup_credits_label.setText("Кредиты (всего) :");

        bup_credits_field.setEditable(false);

        raspred_uchVrem_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Распределение учебного времени"));

        bup_auditorn_label.setText("Аудиторные всего:");

        bup_lection_label.setText("Лекции:");

        bup_practika_label.setText("Практика:");

        bup_individual_label.setText("Индивидуальные:");

        bup_srs_label.setText("СРС:");

        bup_auditorn_field.setEditable(false);

        bup_practika_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bup_practika_fieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout raspred_uchVrem_panelLayout = new javax.swing.GroupLayout(raspred_uchVrem_panel);
        raspred_uchVrem_panel.setLayout(raspred_uchVrem_panelLayout);
        raspred_uchVrem_panelLayout.setHorizontalGroup(
            raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raspred_uchVrem_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(raspred_uchVrem_panelLayout.createSequentialGroup()
                        .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bup_auditorn_label)
                            .addComponent(bup_lection_label)
                            .addComponent(bup_practika_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bup_practika_field)
                            .addComponent(bup_lection_field)
                            .addComponent(bup_auditorn_field, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                    .addGroup(raspred_uchVrem_panelLayout.createSequentialGroup()
                        .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bup_individual_label)
                            .addComponent(bup_srs_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bup_individual_field)
                            .addComponent(bup_srs_field))))
                .addContainerGap())
        );
        raspred_uchVrem_panelLayout.setVerticalGroup(
            raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raspred_uchVrem_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_auditorn_label)
                    .addComponent(bup_auditorn_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_lection_label)
                    .addComponent(bup_lection_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_practika_label)
                    .addComponent(bup_practika_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_individual_label)
                    .addComponent(bup_individual_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_srs_label)
                    .addComponent(bup_srs_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bup_zachet_label.setText("Зачет:");

        bup_ekzamen_label.setText("Экзамен:");

        bup_kursov_label.setText("Курсовая работа:");

        bup_kontol_label.setText("Контр. работа:");

        bup_nir_label.setText("НИР:");

        bup_semestr_label.setText("Семестр:");

        bup_semestr_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        bup_add_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apply.png"))); // NOI18N
        bup_add_save.setText("Сохранить");
        bup_add_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bup_add_saveMouseClicked(evt);
            }
        });

        bup_add_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel_editing.png"))); // NOI18N
        bup_add_cancel.setText("Отмена");
        bup_add_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bup_add_cancelMouseClicked(evt);
            }
        });

        jLabel1.setText("Учебные годы: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bup_disc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bup_clock_label)
                    .addComponent(bup_credits_label)
                    .addComponent(bup_zachet_label)
                    .addComponent(bup_ekzamen_label)
                    .addComponent(bup_kursov_label)
                    .addComponent(bup_kontol_label)
                    .addComponent(bup_nir_label)
                    .addComponent(bup_semestr_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bup_disc_code)
                    .addComponent(bup_clock_field)
                    .addComponent(bup_credits_field)
                    .addComponent(bup_zachet_field)
                    .addComponent(bup_ekzamen_field)
                    .addComponent(bup_kursov_field)
                    .addComponent(bup_kontrol_label)
                    .addComponent(bup_nir_field)
                    .addComponent(bup_semestr_combo, 0, 103, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bup_disс_name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(raspred_uchVrem_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bup_year_s, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bup_year_e, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(bup_add_save)
                .addGap(18, 18, 18)
                .addComponent(bup_add_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_disc_label)
                    .addComponent(bup_disс_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bup_disc_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bup_clock_label)
                            .addComponent(bup_clock_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bup_credits_label)
                            .addComponent(bup_credits_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bup_zachet_label)
                            .addComponent(bup_zachet_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bup_ekzamen_label)
                            .addComponent(bup_ekzamen_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bup_kursov_label)
                            .addComponent(bup_kursov_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bup_kontol_label)
                            .addComponent(bup_kontrol_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bup_nir_label)
                            .addComponent(bup_nir_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(raspred_uchVrem_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_semestr_label)
                    .addComponent(bup_semestr_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(bup_year_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bup_year_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_add_save)
                    .addComponent(bup_add_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bup_add_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bup_add_cancelMouseClicked
        
        dispose();
        
    }//GEN-LAST:event_bup_add_cancelMouseClicked

    private void bup_add_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bup_add_saveMouseClicked
        DisplayBUPYears dbY = new DisplayBUPYears();
        
        String _start = bup_year_s.getSelectedItem().toString();
        String _end = bup_year_e.getSelectedItem().toString();

        String bupYearsId =  dbY.getIdYearsUchGod(_start, _end);
        String bupDiscCode = bup_disc_code.getText();
        String bupVsegoChas = bup_clock_field.getText();
        String bupCreditVsego = bup_credits_field.getText();
        String bupAudChas = bup_auditorn_field.getText();;
        String bupLecChas = bup_lection_field.getText();
        String bupPracChas = bup_practika_field.getText();
        String bupIndChas = bup_individual_field.getText();
        String bupSrsChas = bup_srs_field.getText();
        String bupZachet = bup_zachet_field.getText();
        String bupEkzamen = bup_ekzamen_field.getText();
        String bupKursovRabota = bup_kursov_field.getText();
        String bupKontrRabota = bup_kontrol_label.getText();
        String bupNir = bup_nir_field.getText();
        String bupSemestr = bup_semestr_combo.getSelectedItem().toString();
        
        AddBup addBup = new AddBup();
        
        Boolean isBupCreated = addBup.addBup(bupYearsId, bupDiscCode, bupVsegoChas, 
                bupCreditVsego, bupAudChas, bupLecChas, 
                bupPracChas, bupIndChas,  bupSrsChas, 
                bupZachet, bupEkzamen, bupKursovRabota, 
                bupKontrRabota, bupNir, bupSemestr);
        
        if(isBupCreated != false){
            JOptionPane.showMessageDialog(null, "Запись успешно создано!");
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Проверьте правильность введенных данных!");
        }
    }//GEN-LAST:event_bup_add_saveMouseClicked

    private void bup_disс_namePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_bup_disс_namePopupMenuWillBecomeInvisible
       
        String discName = (String) bup_disс_name.getSelectedItem();
        DisciplineDAO discUtils = new DisciplineDAO();
        String disc_code = discUtils.getDisciplineCode(discName);
        bup_disc_code.setText(disc_code);
        
    }//GEN-LAST:event_bup_disс_namePopupMenuWillBecomeInvisible

    private void bup_clock_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bup_clock_fieldKeyPressed
       int vsegoChas = Integer.parseInt(bup_clock_field.getText());
        
//        Integer lectures = Integer.parseInt(bup_lection_field.getText());
//        Integer practica = Integer.parseInt(bup_auditorn_field.getText());
//        Integer auditorn = lectures + practica;
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            CountClock count = new CountClock();
            Integer credits = count.getCretits(vsegoChas);
            bup_credits_field.setText(credits.toString());
            
//            Integer srs = count.getSRS(vsegoChas, auditorn);
//            bup_srs_field.setText(srs.toString());
            
        }
    }//GEN-LAST:event_bup_clock_fieldKeyPressed

    private void bup_practika_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bup_practika_fieldKeyPressed
        CountClock count = new CountClock();
        Integer vsegoChas = Integer.parseInt(bup_clock_field.getText());
                
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Integer lectures = Integer.parseInt(bup_lection_field.getText());
            Integer practica = Integer.parseInt(bup_practika_field.getText());
            Integer auditorn = lectures + practica;
 
            bup_auditorn_field.setText(auditorn.toString());
            bup_srs_field.setText(count.getSRS(vsegoChas, auditorn).toString());
        }
    }//GEN-LAST:event_bup_practika_fieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bup_add_cancel;
    private javax.swing.JButton bup_add_save;
    private javax.swing.JFormattedTextField bup_auditorn_field;
    private javax.swing.JLabel bup_auditorn_label;
    private javax.swing.JFormattedTextField bup_clock_field;
    private javax.swing.JLabel bup_clock_label;
    private javax.swing.JFormattedTextField bup_credits_field;
    private javax.swing.JLabel bup_credits_label;
    private javax.swing.JTextField bup_disc_code;
    private javax.swing.JLabel bup_disc_label;
    private javax.swing.JComboBox bup_disс_name;
    private javax.swing.JFormattedTextField bup_ekzamen_field;
    private javax.swing.JLabel bup_ekzamen_label;
    private javax.swing.JFormattedTextField bup_individual_field;
    private javax.swing.JLabel bup_individual_label;
    private javax.swing.JLabel bup_kontol_label;
    private javax.swing.JFormattedTextField bup_kontrol_label;
    private javax.swing.JFormattedTextField bup_kursov_field;
    private javax.swing.JLabel bup_kursov_label;
    private javax.swing.JFormattedTextField bup_lection_field;
    private javax.swing.JLabel bup_lection_label;
    private javax.swing.JFormattedTextField bup_nir_field;
    private javax.swing.JLabel bup_nir_label;
    private javax.swing.JFormattedTextField bup_practika_field;
    private javax.swing.JLabel bup_practika_label;
    private javax.swing.JComboBox bup_semestr_combo;
    private javax.swing.JLabel bup_semestr_label;
    private javax.swing.JFormattedTextField bup_srs_field;
    private javax.swing.JLabel bup_srs_label;
    private javax.swing.JComboBox bup_year_e;
    private javax.swing.JComboBox bup_year_s;
    private javax.swing.JFormattedTextField bup_zachet_field;
    private javax.swing.JLabel bup_zachet_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel raspred_uchVrem_panel;
    // End of variables declaration//GEN-END:variables
}
