/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reschetChasov;

import DAO.DisciplineDAO;
import DAO.GroupsDAO;
import DAO.TeacherDAO;
import bup.AddBupForm;
import countClocks.CountClock;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Altynbek
 */
public class AddRaschetChasovForm extends javax.swing.JFrame {

    /**
     * Creates new form AddIndPlanForm
     */
    public AddRaschetChasovForm() {
        initComponents();
        fillTableBup();
        fillDisciplineCombo();
        fillTeacherNames();
        fillGroupsCombo();
    }
    
    
    private void fillDisciplineCombo(){
        
        List<String> discNames = new ArrayList<String>();
        
        DisciplineDAO fill = new DisciplineDAO();
        discNames = fill.getDisciplineNameList();
        
        for(int i=0; i < discNames.size(); i++){
            bup_disс_name.addItem(discNames.get(i));
        }
    }
    
    private void fillTableBup(){
        AddBupForm adbY = new AddBupForm();
        adbY.updateBupTable(bup_table_bup);
    }
    
    private void fillTeacherNames(){
        TeacherDAO tDao = new TeacherDAO();
        List<String> tList = tDao.getTeacherLastNames();
        
        for (int i=0; i < tList.size(); i++){
            teacherLastname_list_combo.addItem(tList.get(i));
        }
    }
    
    private void fillGroupsCombo(){
        GroupsDAO grD = new GroupsDAO();
        List<String> groups = grD.getGroupsList();
        
        for(int i=0; i<groups.size(); i++){
            groupsCombo.addItem(groups.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel_raschet = new javax.swing.JPanel();
        raschet_split_pane = new javax.swing.JSplitPane();
        bup_table_rch = new javax.swing.JPanel();
        bup_table_rch_split = new javax.swing.JScrollPane();
        bup_table_bup = new javax.swing.JTable();
        rch_info_panel = new javax.swing.JPanel();
        common = new javax.swing.JPanel();
        po_raschetu_panel = new javax.swing.JPanel();
        lectures_raschet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        konsult_group = new javax.swing.JTextField();
        group_course_raschet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        grou_student_count = new javax.swing.JTextField();
        konsult_ind = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seminar_raschet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kursov_raschet = new javax.swing.JTextField();
        nir_raschet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        groupsCombo = new javax.swing.JComboBox();
        teacherLastname_list_combo = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        predipl_prac = new javax.swing.JTextField();
        rukov_vkr = new javax.swing.JTextField();
        recenziya_raschet = new javax.swing.JTextField();
        uchastie_v_gak_raschet = new javax.swing.JTextField();
        saveRaschetChasovButoon = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bup_practica_label = new javax.swing.JLabel();
        bup_practica_field = new javax.swing.JTextField();
        po_bup_panel = new javax.swing.JPanel();
        raspred_uchVrem_panel = new javax.swing.JPanel();
        bup_auditorn_label = new javax.swing.JLabel();
        bup_lection_label = new javax.swing.JLabel();
        bup_practika_label = new javax.swing.JLabel();
        bup_individual_label = new javax.swing.JLabel();
        bup_srs_label = new javax.swing.JLabel();
        bup_auditorn_field = new javax.swing.JFormattedTextField();
        bup_lection_field = new javax.swing.JFormattedTextField();
        bup_seminars_field = new javax.swing.JFormattedTextField();
        bup_individual_field = new javax.swing.JFormattedTextField();
        bup_srs_field = new javax.swing.JFormattedTextField();
        bup_nir_label = new javax.swing.JLabel();
        bup_nir_field = new javax.swing.JFormattedTextField();
        bup_kontrol_label = new javax.swing.JFormattedTextField();
        bup_disс_name = new javax.swing.JComboBox();
        bup_zachet_label = new javax.swing.JLabel();
        bup_ekzamen_field = new javax.swing.JFormattedTextField();
        bup_kursov_field = new javax.swing.JFormattedTextField();
        bup_clock_field = new javax.swing.JFormattedTextField();
        bup_credits_field = new javax.swing.JFormattedTextField();
        bup_ekzamen_label = new javax.swing.JLabel();
        bup_disc_label = new javax.swing.JLabel();
        bup_semestr_combo = new javax.swing.JComboBox();
        bup_kursov_label = new javax.swing.JLabel();
        bup_disc_code = new javax.swing.JTextField();
        bup_kontol_label = new javax.swing.JLabel();
        bup_semestr_label = new javax.swing.JLabel();
        bup_credits_label = new javax.swing.JLabel();
        bup_clock_label = new javax.swing.JLabel();
        bup_zachet_field = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Расчет и распределение часов");

        raschet_split_pane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        bup_table_bup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bup_table_bup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bup_table_bupMouseClicked(evt);
            }
        });
        bup_table_rch_split.setViewportView(bup_table_bup);

        javax.swing.GroupLayout bup_table_rchLayout = new javax.swing.GroupLayout(bup_table_rch);
        bup_table_rch.setLayout(bup_table_rchLayout);
        bup_table_rchLayout.setHorizontalGroup(
            bup_table_rchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bup_table_rch_split, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        bup_table_rchLayout.setVerticalGroup(
            bup_table_rchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bup_table_rchLayout.createSequentialGroup()
                .addComponent(bup_table_rch_split, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        raschet_split_pane.setLeftComponent(bup_table_rch);

        rch_info_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        po_raschetu_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("По расчету"));

        jLabel7.setText("НИР(засчитать в нагрузку): ");

        jLabel5.setText("Семинары(засчитать в нагрузку): ");

        jLabel12.setText("Руководство ВКР: ");

        jLabel2.setText("Кол-во студ в гр.:");

        jLabel13.setText("Рецензирование: ");

        jLabel15.setText("Участие в ГАК:");

        jLabel10.setText("Консультатции(инд-х):");

        jLabel6.setText("Курсовая работа(руководство): ");

        jLabel3.setText("Группа:");

        jLabel9.setText("Консультатции(групповых):");

        jLabel8.setText("Преддипл. практика: ");

        groupsCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                groupsComboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel16.setText("Преподаватель: ");

        jLabel4.setText("Лекции(засчитать в нагрузку): ");

        jLabel1.setText("Курс: ");

        saveRaschetChasovButoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apply.png"))); // NOI18N
        saveRaschetChasovButoon.setText("Сохранить");
        saveRaschetChasovButoon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveRaschetChasovButoonMouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel_editing.png"))); // NOI18N
        jButton2.setText("Отмена");

        bup_practica_label.setText("Практика: ");

        javax.swing.GroupLayout po_raschetu_panelLayout = new javax.swing.GroupLayout(po_raschetu_panel);
        po_raschetu_panel.setLayout(po_raschetu_panelLayout);
        po_raschetu_panelLayout.setHorizontalGroup(
            po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                                .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(group_course_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(groupsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                                .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lectures_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kursov_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nir_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(konsult_group, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(konsult_ind, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGap(12, 12, 12)
                                                    .addComponent(seminar_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, po_raschetu_panelLayout.createSequentialGroup()
                                                    .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel15))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rukov_vkr)
                                                        .addComponent(predipl_prac)
                                                        .addComponent(recenziya_raschet)
                                                        .addComponent(uchastie_v_gak_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(grou_student_count, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(111, 111, 111))))
                                    .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(teacherLastname_list_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bup_practica_field, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(saveRaschetChasovButoon)
                        .addGap(135, 135, 135)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bup_practica_label)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        po_raschetu_panelLayout.setVerticalGroup(
            po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(group_course_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(groupsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lectures_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kursov_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nir_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(konsult_group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(konsult_ind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(po_raschetu_panelLayout.createSequentialGroup()
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(grou_student_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(seminar_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(predipl_prac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rukov_vkr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(recenziya_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(uchastie_v_gak_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(teacherLastname_list_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_practica_label)
                    .addComponent(bup_practica_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(po_raschetu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveRaschetChasovButoon)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        po_bup_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("По БУП"));
        po_bup_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        raspred_uchVrem_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Распределение учебного времени"));

        bup_auditorn_label.setText("Аудиторные всего:");

        bup_lection_label.setText("Лекции:");

        bup_practika_label.setText("Семинары:");

        bup_individual_label.setText("Индивидуальные:");

        bup_srs_label.setText("СРС:");

        bup_auditorn_field.setEditable(false);

        javax.swing.GroupLayout raspred_uchVrem_panelLayout = new javax.swing.GroupLayout(raspred_uchVrem_panel);
        raspred_uchVrem_panel.setLayout(raspred_uchVrem_panelLayout);
        raspred_uchVrem_panelLayout.setHorizontalGroup(
            raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raspred_uchVrem_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(raspred_uchVrem_panelLayout.createSequentialGroup()
                        .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bup_auditorn_label)
                            .addComponent(bup_lection_label)
                            .addComponent(bup_practika_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bup_lection_field)
                            .addComponent(bup_seminars_field)
                            .addComponent(bup_auditorn_field, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                    .addGroup(raspred_uchVrem_panelLayout.createSequentialGroup()
                        .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bup_individual_label)
                            .addComponent(bup_srs_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bup_individual_field)
                            .addComponent(bup_srs_field))))
                .addContainerGap())
        );
        raspred_uchVrem_panelLayout.setVerticalGroup(
            raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raspred_uchVrem_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_auditorn_label)
                    .addComponent(bup_auditorn_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_lection_label)
                    .addComponent(bup_lection_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_practika_label)
                    .addComponent(bup_seminars_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_individual_label)
                    .addComponent(bup_individual_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(raspred_uchVrem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bup_srs_label)
                    .addComponent(bup_srs_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        po_bup_panel.add(raspred_uchVrem_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 53, -1, -1));

        bup_nir_label.setText("НИР:");
        po_bup_panel.add(bup_nir_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 226, -1, -1));
        po_bup_panel.add(bup_nir_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 223, 37, -1));
        po_bup_panel.add(bup_kontrol_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 192, 37, -1));

        bup_disс_name.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                bup_disс_namePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        po_bup_panel.add(bup_disс_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 16, 239, -1));

        bup_zachet_label.setText("Зачет:");
        po_bup_panel.add(bup_zachet_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 102, -1, -1));
        po_bup_panel.add(bup_ekzamen_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 130, 37, -1));
        po_bup_panel.add(bup_kursov_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 161, 37, -1));
        po_bup_panel.add(bup_clock_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 42, 37, -1));

        bup_credits_field.setEditable(false);
        po_bup_panel.add(bup_credits_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 68, 37, -1));

        bup_ekzamen_label.setText("Экзамен:");
        po_bup_panel.add(bup_ekzamen_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 133, -1, -1));

        bup_disc_label.setText("Код дисциплины");
        po_bup_panel.add(bup_disc_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 19, 94, -1));

        bup_semestr_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        po_bup_panel.add(bup_semestr_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 254, -1, -1));

        bup_kursov_label.setText("Курсовая работа:");
        po_bup_panel.add(bup_kursov_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 164, -1, -1));

        bup_disc_code.setEditable(false);
        po_bup_panel.add(bup_disc_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 16, 91, -1));

        bup_kontol_label.setText("Контр. работа:");
        po_bup_panel.add(bup_kontol_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 195, -1, -1));

        bup_semestr_label.setText("Семестр:");
        po_bup_panel.add(bup_semestr_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 254, -1, -1));

        bup_credits_label.setText("Кредиты (всего) :");
        po_bup_panel.add(bup_credits_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 71, -1, -1));

        bup_clock_label.setText("Всего час:");
        po_bup_panel.add(bup_clock_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 45, -1, -1));
        po_bup_panel.add(bup_zachet_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 99, 37, -1));

        javax.swing.GroupLayout commonLayout = new javax.swing.GroupLayout(common);
        common.setLayout(commonLayout);
        commonLayout.setHorizontalGroup(
            commonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(po_raschetu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(po_bup_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );
        commonLayout.setVerticalGroup(
            commonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(po_bup_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(commonLayout.createSequentialGroup()
                        .addComponent(po_raschetu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout rch_info_panelLayout = new javax.swing.GroupLayout(rch_info_panel);
        rch_info_panel.setLayout(rch_info_panelLayout);
        rch_info_panelLayout.setHorizontalGroup(
            rch_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rch_info_panelLayout.createSequentialGroup()
                .addComponent(common, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
        );
        rch_info_panelLayout.setVerticalGroup(
            rch_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rch_info_panelLayout.createSequentialGroup()
                .addComponent(common, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        raschet_split_pane.setBottomComponent(rch_info_panel);

        javax.swing.GroupLayout main_panel_raschetLayout = new javax.swing.GroupLayout(main_panel_raschet);
        main_panel_raschet.setLayout(main_panel_raschetLayout);
        main_panel_raschetLayout.setHorizontalGroup(
            main_panel_raschetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1117, Short.MAX_VALUE)
            .addGroup(main_panel_raschetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(main_panel_raschetLayout.createSequentialGroup()
                    .addComponent(raschet_split_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        main_panel_raschetLayout.setVerticalGroup(
            main_panel_raschetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(main_panel_raschetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(raschet_split_pane, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_panel_raschet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel_raschet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1137, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bup_table_bupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bup_table_bupMouseClicked
        int row = bup_table_bup.getSelectedRow();
        String disc_code = (bup_table_bup.getValueAt(row, 0).toString());
        String disc_name = (bup_table_bup.getValueAt(row, 1).toString());
        String vsego_ch = (bup_table_bup.getValueAt(row, 2).toString());
        String credits = (bup_table_bup.getValueAt(row, 3).toString());
        String auditorn = (bup_table_bup.getValueAt(row, 4).toString());
        String lectures = (bup_table_bup.getValueAt(row, 5).toString());
        String practica = (bup_table_bup.getValueAt(row, 6).toString());
        String indiv = (bup_table_bup.getValueAt(row, 7).toString());
        String srs = (bup_table_bup.getValueAt(row, 8).toString());
        String zachet = (bup_table_bup.getValueAt(row, 9).toString());
        String ekzamen = (bup_table_bup.getValueAt(row, 10).toString());
        String kurs_rabota = (bup_table_bup.getValueAt(row, 11).toString());
        String kont_rabota = (bup_table_bup.getValueAt(row, 12).toString());
        String nir = (bup_table_bup.getValueAt(row, 13).toString());
        String semestr = (bup_table_bup.getValueAt(row, 14).toString());
        
        bup_disc_code.setText(disc_code);
        bup_disс_name.setSelectedItem(disc_name);
        bup_clock_field.setText(vsego_ch);
        bup_credits_field.setText(credits);
        bup_auditorn_field.setText(auditorn);
        bup_lection_field.setText(lectures);
        bup_seminars_field.setText(practica);
        bup_individual_field.setText(indiv);
        bup_srs_field.setText(srs);
        bup_zachet_field.setText(zachet);
        bup_ekzamen_field.setText(ekzamen);
        bup_kursov_field.setText(kurs_rabota);
        bup_kontrol_label.setText(kont_rabota);
        bup_nir_field.setText(nir);
        bup_semestr_combo.setSelectedItem(semestr);
        
    }//GEN-LAST:event_bup_table_bupMouseClicked

    private void bup_disс_namePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_bup_disс_namePopupMenuWillBecomeInvisible

    }//GEN-LAST:event_bup_disс_namePopupMenuWillBecomeInvisible

    private void groupsComboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_groupsComboPopupMenuWillBecomeInvisible
        String grCode = groupsCombo.getSelectedItem().toString();
        
        GroupsDAO grD = new GroupsDAO();
        Integer semestr =Integer.parseInt(grD.getGroupInfo("group_semestr", grCode));
        group_course_raschet.setText(grD.getGroupCourse(semestr).toString());
        grou_student_count.setText(grD.getStudentCountInGroup(grCode).toString());
        
    }//GEN-LAST:event_groupsComboPopupMenuWillBecomeInvisible

    private void saveRaschetChasovButoonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveRaschetChasovButoonMouseClicked
       AddRaschetChasov addRaschet = new AddRaschetChasov();
       TeacherDAO teacher = new TeacherDAO();
       
       String discCode = bup_disc_code.getText();  
       String groupCode = groupsCombo.getSelectedItem().toString();
       String studKolv = grou_student_count.getText();
       String semestr = bup_semestr_combo.getSelectedItem().toString();
       String course = group_course_raschet.getText();
       String bupLection = bup_lection_field.getText();
       String lecturesRaschet = lectures_raschet.getText();
       String bupSeminars = bup_seminars_field.getText();
       String seminarRaschet = seminar_raschet.getText();
       String bupKursov = bup_kursov_field.getText();
       String kursovRaschet = kursov_raschet.getText();
       String ects = bup_credits_field.getText();
       String bupNir = bup_nir_field.getText();
       String nirRaschet = nir_raschet.getText();
       String bupInd = bup_individual_field.getText();  
       String konsultGroup = konsult_group.getText();
       String konsultInd = konsult_ind.getText();
       String bupSrs = bup_srs_field.getText();
       String bupPrac = bup_practica_field.getText();
       String bupZachet = bup_zachet_field.getText();
       String bupEkzamen = bup_ekzamen_field.getText();
       String preddiplPrac = predipl_prac.getText();
       String rukovVkr = rukov_vkr.getText();
       String recenziya = recenziya_raschet.getText();
       String gakUchastie = uchastie_v_gak_raschet.getText();
       String vsegoChas = bup_clock_field.getText();
       String bup_kontrRabota = bup_kontrol_label.getText();
       
       String teacherId = teacher.getTeacherId(teacherLastname_list_combo.getSelectedItem().toString()).toString();
       
       
       Boolean success = addRaschet.addRaschetChasov(discCode, groupCode, studKolv, 
               semestr, course, bupLection, lecturesRaschet, bupSeminars, seminarRaschet, 
               bupKursov, kursovRaschet, bup_kontrRabota, bupNir, nirRaschet, bupInd, konsultGroup, 
               konsultInd, bupSrs , bupPrac, bupZachet, bupEkzamen, preddiplPrac, 
               rukovVkr, recenziya, gakUchastie, vsegoChas, ects, teacherId);
       
       if (success != false){
           JOptionPane.showMessageDialog(null, "Данные успешно сохранены!");
       }else{
           JOptionPane.showMessageDialog(null, "Проверьте правильность введенных вами данных!");
       }
       
               
    }//GEN-LAST:event_saveRaschetChasovButoonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRaschetChasovForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRaschetChasovForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRaschetChasovForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRaschetChasovForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRaschetChasovForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField bup_auditorn_field;
    private javax.swing.JLabel bup_auditorn_label;
    private javax.swing.JFormattedTextField bup_clock_field;
    private javax.swing.JLabel bup_clock_label;
    private javax.swing.JFormattedTextField bup_credits_field;
    private javax.swing.JLabel bup_credits_label;
    private javax.swing.JTextField bup_disc_code;
    private javax.swing.JLabel bup_disc_label;
    private javax.swing.JComboBox bup_disс_name;
    private javax.swing.JFormattedTextField bup_ekzamen_field;
    private javax.swing.JLabel bup_ekzamen_label;
    private javax.swing.JFormattedTextField bup_individual_field;
    private javax.swing.JLabel bup_individual_label;
    private javax.swing.JLabel bup_kontol_label;
    private javax.swing.JFormattedTextField bup_kontrol_label;
    private javax.swing.JFormattedTextField bup_kursov_field;
    private javax.swing.JLabel bup_kursov_label;
    private javax.swing.JFormattedTextField bup_lection_field;
    private javax.swing.JLabel bup_lection_label;
    private javax.swing.JFormattedTextField bup_nir_field;
    private javax.swing.JLabel bup_nir_label;
    private javax.swing.JTextField bup_practica_field;
    private javax.swing.JLabel bup_practica_label;
    private javax.swing.JLabel bup_practika_label;
    private javax.swing.JComboBox bup_semestr_combo;
    private javax.swing.JLabel bup_semestr_label;
    private javax.swing.JFormattedTextField bup_seminars_field;
    private javax.swing.JFormattedTextField bup_srs_field;
    private javax.swing.JLabel bup_srs_label;
    private javax.swing.JTable bup_table_bup;
    private javax.swing.JPanel bup_table_rch;
    private javax.swing.JScrollPane bup_table_rch_split;
    private javax.swing.JFormattedTextField bup_zachet_field;
    private javax.swing.JLabel bup_zachet_label;
    private javax.swing.JPanel common;
    private javax.swing.JTextField grou_student_count;
    private javax.swing.JTextField group_course_raschet;
    private javax.swing.JComboBox groupsCombo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField konsult_group;
    private javax.swing.JTextField konsult_ind;
    private javax.swing.JTextField kursov_raschet;
    private javax.swing.JTextField lectures_raschet;
    private javax.swing.JPanel main_panel_raschet;
    private javax.swing.JTextField nir_raschet;
    private javax.swing.JPanel po_bup_panel;
    private javax.swing.JPanel po_raschetu_panel;
    private javax.swing.JTextField predipl_prac;
    private javax.swing.JSplitPane raschet_split_pane;
    private javax.swing.JPanel raspred_uchVrem_panel;
    private javax.swing.JPanel rch_info_panel;
    private javax.swing.JTextField recenziya_raschet;
    private javax.swing.JTextField rukov_vkr;
    private javax.swing.JButton saveRaschetChasovButoon;
    private javax.swing.JTextField seminar_raschet;
    private javax.swing.JComboBox teacherLastname_list_combo;
    private javax.swing.JTextField uchastie_v_gak_raschet;
    // End of variables declaration//GEN-END:variables
}
